title: Sanguine Spirits
email: woutervs@hotmail.com
description: >-
  Sanguine Spirits, where every sip runs deep.
  Dark, elegant cocktail recipes — pure indulgence, zero nonsense.
baseurl: "/Sanguine-Spirits"
url: "https://sangu.be"

# Build settings
theme: minima
plugins:
  - jekyll-feed

google_analytics:
github: https://github.com/SanguPackage/Sanguine-Spirits


exclude:
  - generate-cocktail-pages.rb
  - LICENSE
  - pre-commit
  - README.md
